# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: salesforce/salesforcedx:latest-rc-full

pipelines:
  pull-requests:
    '**':
      - step:
          name: Validate on DESTINATION environment
          condition:
              changesets:
                  includePaths:
                    # any changes in project directory
                    - "force-app/**"
          caches:
            - pip 
          script:
            - chmod +x scripts/pullrequest.sh
            - scripts/pullrequest.sh
  branches:   
    release/dev:
    - step:
        name: Deploy DEV
        condition:
              changesets:
                  includePaths:
                    # any changes in project directory
                    - "force-app/**"
        deployment: DEV-SF
        caches:
          - pip
        script:
          - sfdx force:auth:jwt:grant --clientid $SFDC_DEV_CONSUMER_KEY --username $SFDC_DEV_USERNAME --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_SANDBOX_INSTANCE_URL
          - chmod +x scripts/additionalInstallations.sh
          - chmod +x scripts/getTestClassesName.sh
          - chmod +x scripts/deploy.sh
          - chmod +x scripts/checkOnlyDeletions.sh
          - unzip pmd/pmd-bin-6.42.0.zip -d pmd
          - scripts/additionalInstallations.sh
          - mkdir changed-sources
          - sfdx sgd:source:delta -s force-app --to HEAD --from HEAD^ --output ./changed-sources --generate-delta
          - scripts/checkOnlyDeletions.sh
          #===Make sure there is no PMD error with a high priority===
          - pmd/pmd-bin-6.42.0/bin/run.sh pmd --minimum-priority $PMD_MINIMUM_PRIORITY -d ./changed-sources -R pmd/custom-apex-rules.xml -f textcolor -l apex
          - scripts/getTestClassesName.sh
          - scripts/deploy.sh 
    release/uat:
      - step:
          name: Deploy UAT
          condition:
              changesets:
                  includePaths:
                    # any changes in project directory
                    - "force-app/**"
          deployment: UAT-SF
          caches:
            - pip
          script:
            - sfdx force:auth:jwt:grant --clientid $SFDC_UAT_CONSUMER_KEY --username $SFDC_UAT_USERNAME --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_SANDBOX_INSTANCE_URL
            - chmod +x scripts/additionalInstallations.sh
            - chmod +x scripts/getTestClassesName.sh
            - chmod +x scripts/deploy.sh
            - chmod +x scripts/checkOnlyDeletions.sh
            - unzip pmd/pmd-bin-6.42.0.zip -d pmd
            - scripts/additionalInstallations.sh
            - mkdir changed-sources
            - sfdx sgd:source:delta -s force-app --to HEAD --from HEAD^ --output ./changed-sources --generate-delta
            - scripts/checkOnlyDeletions.sh
            #===Make sure there is no PMD error with a high priority===
            - pmd/pmd-bin-6.42.0/bin/run.sh pmd --minimum-priority $PMD_MINIMUM_PRIORITY -d ./changed-sources -R pmd/custom-apex-rules.xml -f textcolor -l apex
            - scripts/getTestClassesName.sh
            - scripts/deploy.sh  
    release/hotfix:
      - step:
          name: Deploy HOTFIX
          condition:
              changesets:
                  includePaths:
                    # any changes in project directory
                    - "force-app/**"
          deployment: HOTFIX-SF
          caches:
            - pip
          script:
            - sfdx force:auth:jwt:grant --clientid $SFDC_HOTFIX_CONSUMER_KEY --username $SFDC_HOTFIX_USERNAME --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_SANDBOX_INSTANCE_URL
            - chmod +x scripts/additionalInstallations.sh
            - chmod +x scripts/getTestClassesName.sh
            - chmod +x scripts/deploy.sh
            - chmod +x scripts/checkOnlyDeletions.sh
            - unzip pmd/pmd-bin-6.42.0.zip -d pmd
            - scripts/additionalInstallations.sh
            - mkdir changed-sources
            - sfdx sgd:source:delta -s force-app --to HEAD --from HEAD^ --output ./changed-sources --generate-delta
            - scripts/checkOnlyDeletions.sh
            #===Make sure there is no PMD error with a high priority===
            - pmd/pmd-bin-6.42.0/bin/run.sh pmd --minimum-priority $PMD_MINIMUM_PRIORITY -d ./changed-sources -R pmd/custom-apex-rules.xml -f textcolor -l apex
            - scripts/getTestClassesName.sh
            - scripts/deploy.sh    
    main:
      - step:
          name: Deploy PROD
          condition:
              changesets:
                  includePaths:
                    # any changes in project directory
                    - "force-app/**"
          deployment: PROD-SF
          caches:
            - pip
          script:
            - sfdx force:auth:jwt:grant --clientid $SFDC_PROD_CONSUMER_KEY --username $SFDC_PROD_USERNAME --jwtkeyfile keys/server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_PROD_INSTANCE_URL
            - chmod +x scripts/additionalInstallations.sh
            - chmod +x scripts/getTestClassesName.sh
            - chmod +x scripts/deploy.sh
            - chmod +x scripts/checkOnlyDeletions.sh
            - unzip pmd/pmd-bin-6.42.0.zip -d pmd
            - scripts/additionalInstallations.sh
            - mkdir changed-sources
            - sfdx sgd:source:delta -s force-app --to HEAD --from HEAD^ --output ./changed-sources --generate-delta
            - scripts/checkOnlyDeletions.sh
            #===Make sure there is no PMD error with a high priority===
            - pmd/pmd-bin-6.42.0/bin/run.sh pmd --minimum-priority $PMD_MINIMUM_PRIORITY -d ./changed-sources -R pmd/custom-apex-rules.xml -f textcolor -l apex
            - scripts/getTestClassesName.sh
            - scripts/deploy.sh
